#!/usr/bin/env bash

BASE=/home/moritz/git

#ARDUINO=$BASE/arduino/
#AUCA=$BASE/auca/
C_PROJECTS=$BASE/c_projects/
MISC_FILES=$BASE/misc_files/
#QMK_SOURCE=$BASE/qmk_source/
#RASPBERRY_PI=$BASE/raspberry_pi/
#WEATHER_PI=$BASE/weather_pi/
#WEATHER_PI_DEV=$BASE/weather_pi_dev/
PRIMES=$BASE/primes

echo " "

for repo in $C_PROJECTS $MISC_FILES $PRIMES; do
  cd $repo
  echo "$repo"
  git up  
  cd $BASE
  echo " "
done

